name: One Thought at a Time
favicon: null
layout_spectrum: 0.49554
typography_spectrum: 0.99911
title: One Thought at a Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8eb83a'
    - '#b5d069'
    - '#3b1200'
    - '#7f6f32'
    - '#eec36c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
