name: One Thought at a Time
favicon: null
layout_spectrum: 0.31003424688242376
typography_spectrum: 0.2751746065914631
title: The ramblings of an old man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.11698524421080947
  lightness: 0.5403758517932147
  saturation: 0.3005317561328411
  rhythmicContrast: 0.5864441429730505
purpose: []
