name: One Thought at a Time
favicon: null
layout_spectrum: 0.49554
typography_spectrum: 0.99911
title: One Thought at a Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#999999'
    - '#fdfdfd'
    - '#bd821e'
    - '#92420d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
