name: One Thought at a Time
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00532
title: One Thought at a Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: onethoughtatatime.org
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#867156'
    - '#0e0f11'
    - '#5583bf'
    - '#9ab3dc'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
